import AppKit

/// Watches the general pasteboard and keeps the most recent clippings.
///
/// macOS posts no notification when the pasteboard changes, so the only way to
/// observe it is to poll `changeCount` — which is cheap, and unlike reading the
/// contents it never trips the system's paste privacy alert.
final class ClipboardMonitor: ObservableObject {

    struct Clipping: Identifiable, Equatable {
        let id = UUID()
        let text: String

        /// Collapsed to a single line for the popover row.
        var preview: String {
            text.trimmingCharacters(in: .whitespacesAndNewlines)
                .replacingOccurrences(of: "\n", with: " ")
                .replacingOccurrences(of: "\t", with: " ")
        }

        static func == (lhs: Clipping, rhs: Clipping) -> Bool { lhs.text == rhs.text }
    }

    static let capacity = 10

    @Published private(set) var clippings: [Clipping] = []

    private let pasteboard = NSPasteboard.general
    private let defaultsKey = "ClipStack.history"
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Password managers and similar mark their clippings with these so history
    /// tools skip them. Honouring it is the difference between a clipboard
    /// manager and a password logger.
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
        clippings = (UserDefaults.standard.array(forKey: defaultsKey) as? [String] ?? [])
            .map(Clipping.init(text:))
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: Capture

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.ignoredTypes) else { return }

        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        record(text)
    }

    private func record(_ text: String) {
        let clipping = Clipping(text: text)
        var updated = clippings
        updated.removeAll { $0 == clipping }   // re-copying an old item promotes it
        updated.insert(clipping, at: 0)
        if updated.count > Self.capacity { updated.removeLast(updated.count - Self.capacity) }
        clippings = updated
        persist()
    }

    private func persist() {
        UserDefaults.standard.set(clippings.map(\.text), forKey: defaultsKey)
    }

    // MARK: Actions

    /// Put a clipping back on the pasteboard. The next poll promotes it to the
    /// top of the list, which is what you want after reaching for an old one.
    func copy(_ clipping: Clipping) {
        pasteboard.clearContents()
        pasteboard.setString(clipping.text, forType: .string)
    }

    func clear() {
        clippings = []
        persist()
    }
}
